### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by youngmanalive** [youngmanalive/fliqr#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components and Containers
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by andywynkoop** [comment]
Hey Nathan,
Here are a few things to change for the user auth MVP. 
- [ ] Add the link to the live site on your wiki
- [ ] Remove redux logger and all console logs before pushing to production
- [ ] Password fields should be `type: password` so no one can spy over your shoulder
- [ ] When I go to a random route like `/sajhdflhliaeliewhvriludhrvwe`, I should see either a 404 page or get redirected back to `/`
This looks awesome so far, probably the first user auth mvp that I couldn't break easily, nice work!
